### ISSUE TITLE
执行报这个错

### ISSUE THREAD

**Issue by Scott1995** [bigrocs/escpos-win#2]
$ node download.js
D:\demo\project\print\node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: \\?\D:\demo\project\print\node_modules\node-escpos-win\build\Release\addo
n.node is not a valid Win32 application.
\\?\D:\demo\project\print\node_modules\node-escpos-win\build\Release\addon.node
?[90m    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1307
:18)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:1105:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:967:14)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:1145:19)?[39m
?[90m    at require (internal/modules/cjs/helpers.js:75:18)?[39m
    at bindings (D:\demo\project\print\node_modules\?[4mbindings?[24m\bindings.j
s:112:48)
    at win32Escpos (D:\demo\project\print\node_modules\?[4mnode-escpos-win?[24m\
index.js:3:40)
    at Object.<anonymous> (D:\demo\project\print\node_modules\?[4mnode-escpos-wi
n?[24m\index.js:35:18)
?[90m    at Module._compile (internal/modules/cjs/loader.js:1256:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:1
0)?[39m

这个错误是win32的问题吗

**Comment by bigrocs** [comment]
编译不对或者没有编译

**Comment by bigrocs** [comment]
node什么版本

**Comment by Scott1995** [comment]
14.15.1

**Comment by bigrocs** [comment]
重新 npm i 试试吧

**Comment by bigrocs** [comment]
实在不行你可以更新  node 10.15 的版本试试
新版本有时候 构建不那么稳定

**Comment by Scott1995** [comment]
好的 我试一下
